# Generated by Django 3.1.3 on 2020-11-30 07:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_due', models.DateField(blank=True, default=datetime.datetime.today)),
                ('assign_to', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='tasktrackerApp.worker')),
            ],
        ),
    ]
