# Generated by Django 3.1.3 on 2020-11-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrackerApp', '0002_task_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
    ]
