# Generated by Django 3.1.2 on 2020-11-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrackerApp', '0003_auto_20201130_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_name',
        ),
    ]
