# Generated by Django 3.1.2 on 2020-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrackerApp', '0005_task_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='experience',
        ),
        migrations.AddField(
            model_name='worker',
            name='level',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Hire', 'Hire'), ('Supervisor', 'Supervisor')], default='Hire', max_length=100),
            preserve_default=False,
        ),
    ]
