# Generated by Django 3.1.2 on 2020-12-04 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrackerApp', '0006_auto_20201201_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 3, 21, 21, 58, 423539)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
